export const createTypes = {
    GET_CARD_DETAILS: 'GET_CARD_DETAILS',
    GET_CARD_DETAILS_REQUEST: 'GET_CARD_DETAILS_REQUEST',
    GET_CARD_DETAILS_SUCCESS: 'GET_CARD_DETAILS_SUCCESS',
    GET_CARD_DETAILS_FAILURE: 'GET_CARD_DETAILS_FAILURE',
}