export const createTypes = {
    GET_CARD_DETAILS: 'GET_CARD_DETAILS',
    GET_CARD_DETAILS_REQUEST: 'GET_CARD_DETAILS_REQUEST',
    GET_CARD_DETAILS_SUCCESS: 'GET_CARD_DETAILS_SUCCESS',
    GET_CARD_DETAILS_FAILURE: 'GET_CARD_DETAILS_FAILURE',

    SET_CARD: 'SET_CARD',
    SET_CARD_REQUEST: 'SET_CARD_REQUEST',
    SET_CARD_SUCCESS: 'SET_CARD_SUCCESS',
    SET_CARD_FAILURE: 'SET_CARD_FAILURE',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

    SET_CATEGORY: 'SET_CATEGORY',
    SET_CATEGORY_REQUEST: 'SET_CATEGORY_REQUEST',
    SET_CATEGORY_SUCCESS: 'SET_CATEGORY_SUCCESS',
    SET_CATEGORY_FAILURE: 'SET_CATEGORY_FAILURE',

    ADD_CART:'ADD_CART',
    ADD_CART_REQUEST:'ADD_CART_REQUEST',
    ADD_CART_SUCCESS:'ADD_CART_SUCCESS',
    ADD_CART_FAILURE:'ADD_CART_FAILURE',
}